name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: make
      
  test:
    
    name: Test
    needs: [build]
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Clone Criterion
        working-directory: /tmp
        run: git clone --recursive https://github.com/Snaipe/Criterion.git --branch=master --depth=1
      - name: Build Criterion
        working-directory: /tmp/Criterion
        run: mkdir build && cd Criterion/build && cmake .. && cmake --build .
      - name: Install Criterion
        working-directory: /tmp/Criterion/build
        run: make install
      - name: Run tests
        run: make tests_run
